### PR TITLE
Suggested Edits 

### PR DESCRIPTION
**Pull request by cstays**
Some spelling and messaging changes: I don't necessarily agree that the best way for someone to show us who they are is through their code, but I do believe it is a good way.

### CODE REVIEW

**Comment by benhanzl** [comment]
Good catch :+1:

**Comment by brainimus** [comment]
Do we think the link in the first sentence under IZEA Engineering should link to the exchange or to something on the corporate site?  I felt like when I clicked on it I'd go to a place to learn more about IZEA Engineering but instead went to a sign up page.  I don't have a great destination on the corporate site to send people to though.

**Comment by cstays** [comment]
@brainimus When we (create) and launch the engineering blog we can send people to there?

**Comment by brainimus** [comment]
That works for me!  I just thought it felt weird to click on "IZEA Engineering" and not end up on an engineering destination.  :+1:

**Pull request merged**
